import { chromium } from 'playwright-core';
const CH=process.env.HOME+'/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing';
const b=await chromium.launch({executablePath:CH});
const p=await b.newPage({viewport:{width:1512,height:982}});
p.on('requestfailed',r=>console.log('FAIL',r.url().split('/').pop(),'->',r.failure()&&r.failure().errorText));
p.on('response',r=>{if(r.status()>=400)console.log('HTTP',r.status(),r.url().split('/').pop());});
await p.goto('http://localhost:8080/',{waitUntil:'networkidle'});
await p.waitForTimeout(2500);
console.log('fertig');
await p.close(); await b.close();
